void pushTS(char name [16],int isConst);
void popTS();
void printTS();
void printTemp();
void TSinit();
int getSommet();
int popTemp();
int pushTemp();
int findAddr(char name[16]);
int isSymbConst(int adr);
