webtalk_init -webtalk_dir /home/a_dubois/Bureau/4_I/Sys_info/projet_processeur/projet_processeur.sim/sim_1/behav/xsim/xsim.dir/Test_Processeur_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun  1 17:25:40 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bad28e37-53b7-41ed-9909-6b6937f1d1a1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a12ed03533ae451b81149428f0a7fb1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "240" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122660_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3115027711 -regid "" -xml /home/a_dubois/Bureau/4_I/Sys_info/projet_processeur/projet_processeur.sim/sim_1/behav/xsim/xsim.dir/Test_Processeur_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/a_dubois/Bureau/4_I/Sys_info/projet_processeur/projet_processeur.sim/sim_1/behav/xsim/xsim.dir/Test_Processeur_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/a_dubois/Bureau/4_I/Sys_info/projet_processeur/projet_processeur.sim/sim_1/behav/xsim/xsim.dir/Test_Processeur_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
